### Get the working directory

In [1]:
%pwd

'/home/sara/0.W'

### imports a script into a code cell

In [ ]:
%load script.py

### Run a Python script inside IPython

In [ ]:
%run script.py

In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [9]:
x= np.array([1,4,7,2,5,8, 3,6,9])

In [10]:
x

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [11]:
x.dtype

dtype('int64')

In [12]:
x.ndim

1

In [13]:
x.size

9

In [14]:
x.shape

(9,)

In [15]:
x.dtype, x.shape, x.ndim, x.size

(dtype('int64'), (9,), 1, 9)

In [16]:
y = np.array([301, 2.55, 6.22])

In [18]:
y.dtype, y.shape, y.ndim, y.size

(dtype('float64'), (3,), 1, 3)

In [19]:
z = np.array([3.1, 2.55, 6.22], dtype= int)

In [20]:
z.dtype

dtype('int64')

In [21]:
z

array([3, 2, 6])

### Creating Arrays from Scratch

In [23]:
m = np.zeros(15, dtype=int)

In [24]:
m

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
m.shape, m.ndim

((15,), 1)

In [26]:
n = np.ones((3, 5), dtype=float)

In [27]:
n

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
n.shape, n.ndim

((3, 5), 2)

In [29]:
n.size

15

In [31]:
 j = np.full((2, 5), 3.14)

In [32]:
j

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [34]:
j.shape, j.ndim

((2, 5), 2)

In [35]:
j.size

10

In [36]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 30, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [37]:
# Create an array of five values evenly spaced between 0 and 1        
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [38]:
# Create a 4x2 array of uniformly distributed
# random values between 0 and 1
np.random.random((4, 2))

array([[0.89648815, 0.21751466],
       [0.57307871, 0.75832782],
       [0.1380271 , 0.95980695],
       [0.62564963, 0.95270671]])

In [39]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (2, 3))

array([[ 0.95528646,  1.17221593, -1.86529569],
       [-0.16689473,  0.06158228, -0.59280247]])

In [40]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (5, 2))

array([[7, 0],
       [2, 3],
       [4, 9],
       [0, 9],
       [1, 3]])

In [42]:
# Create a 3x3 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [45]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty((5, 2))

array([[3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14],
       [3.14, 3.14]])

In [46]:
np.empty((3))

array([1., 1., 1.])

## NumPy Standard Data Types

We can define data types using a **string** or **NumPy object**

In [47]:
np.zeros(10, dtype='int16')
#or
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

 ### NumPy Arrays manipulations

**Attributes of arrays**: Determining the size, shape, memory consumption, and data types of arrays <br> <br>
**Indexing of arrays**: Getting and setting the value of individual array elements <br> <br>
**Slicing of arrays**: Getting and setting smaller subarrays within a larger array <br> <br>
**Reshaping of arrays**:  Changing the shape of a given array <br> <br>
**Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many

In [48]:
import numpy as np
np.random.seed(1980)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array (1 row and 6 column)
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array ( 3 rows and 4 columns)
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array (3*(4 rows and 5 columns))

In [49]:
x1

array([0, 8, 8, 3, 1, 8])

In [50]:
x2

array([[6, 4, 2, 9],
       [5, 3, 1, 4],
       [1, 2, 3, 8]])

In [51]:
x3

array([[[4, 4, 8, 8, 7],
        [5, 1, 9, 9, 7],
        [6, 7, 0, 8, 0],
        [7, 8, 3, 7, 2]],

       [[6, 5, 5, 8, 2],
        [9, 7, 4, 9, 1],
        [3, 0, 9, 4, 1],
        [5, 1, 8, 4, 7]],

       [[3, 0, 6, 4, 0],
        [0, 1, 4, 9, 7],
        [2, 6, 7, 0, 9],
        [9, 4, 4, 3, 6]]])

In [52]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


# Array Indexing: Accessing Single Elements

In a one-dimensional array, you can access the ith value (counting from zero) by specifying the desired index in square brackets, just as with Python lists:

In [53]:
# one-dimensional array
x1

array([0, 8, 8, 3, 1, 8])

In [54]:
x1[0]

0

In [55]:
x1[5]

8

In [56]:
x1.size

6

## To index from the end of the array, you can use negative indices:

In [57]:
x1[-1]

8

In [58]:
x1[-2]

1

## In a multidimensional array, you access items using a comma-separated tuple of indices:

In [59]:
# two-dimensional array
x2

array([[6, 4, 2, 9],
       [5, 3, 1, 4],
       [1, 2, 3, 8]])

In [63]:
# x2[row, column] ---> counting from zero

x2[2,1]
# row 3 , column 2

2

In [64]:
 x2[1, -1]

4

### We can also modify values using any of the above index notation:

In [65]:
x2[0, 0] = 25
x2

array([[25,  4,  2,  9],
       [ 5,  3,  1,  4],
       [ 1,  2,  3,  8]])

# 3D Array Indexing

In [66]:
# x3[number, row, column]  ---> : means all items
x3

array([[[4, 4, 8, 8, 7],
        [5, 1, 9, 9, 7],
        [6, 7, 0, 8, 0],
        [7, 8, 3, 7, 2]],

       [[6, 5, 5, 8, 2],
        [9, 7, 4, 9, 1],
        [3, 0, 9, 4, 1],
        [5, 1, 8, 4, 7]],

       [[3, 0, 6, 4, 0],
        [0, 1, 4, 9, 7],
        [2, 6, 7, 0, 9],
        [9, 4, 4, 3, 6]]])

In [69]:
# first element of 3d array
print(x3[0,:,:])

[[4 4 8 8 7]
 [5 1 9 9 7]
 [6 7 0 8 0]
 [7 8 3 7 2]]


In [71]:
# second element of 3d array
print(x3[1,:,:])

[[6 5 5 8 2]
 [9 7 4 9 1]
 [3 0 9 4 1]
 [5 1 8 4 7]]


### Indexing second row of each matrix in 3d  array

In [72]:
print(x3[:,1,:])

[[5 1 9 9 7]
 [9 7 4 9 1]
 [0 1 4 9 7]]


# Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; 
### To access a slice of an array x, use this:

### x[<font color="red">start</font>:<font color="blue">stop</font>:<font color="green">step</font>]


If any of these are unspecified, they default to the values **start=0**, **stop=size of dimension**, **step=1**. We’ll take a look at accessing subarrays in one dimension and in multiple dimensions.
### One-dimensional subarrays

In [73]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
 x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [76]:
 x[6:]  # # elements after index 6

array([6, 7, 8, 9])

In [78]:
x[4:7]  # from 4 to 7 element

array([4, 5, 6])

In [79]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [81]:
x[5::2]  # every other element, starting at index 5

array([5, 7, 9])

A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [83]:
x[::-1]  # all elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [87]:
x[6::-2]  # reversed every other from index 6

array([6, 4, 2, 0])

  ## <font color = "red"> Very important </font>

``print(x[k, :]) ``
<br>
The colon can be thought of as an all elements character. So, the preceding statement actually means Print all the characters for the k th row. Similarly, a column can be accessed with ``x[:,k]``. Reversing an array is also similar to reversing a list, such as ``x[::-1]``.

In [242]:
x = np.random.rand(100,10)
x.shape

(100, 10)

In [243]:
x.ndim

2

Now, let us extract the first five rows of the array and assign them to variable y.

In [244]:
y = x[:5, :]

In [245]:
y.shape

(5, 10)

## Multidimensional subarrays

Multidimensional slices work in the same way, with multiple slices separated by commas. For example:

In [88]:
x2

array([[25,  4,  2,  9],
       [ 5,  3,  1,  4],
       [ 1,  2,  3,  8]])

In [89]:
x2[:2, :3]  # two rows(rows 0 and 1), three columns (columns 0 , 1, 2)

array([[25,  4,  2],
       [ 5,  3,  1]])

In [90]:
x2[:3, ::2]  # all rows, every other column

array([[25,  2],
       [ 5,  1],
       [ 1,  3]])

In [91]:
x2[::-1, ::-1]

array([[ 8,  3,  2,  1],
       [ 4,  1,  3,  5],
       [ 9,  2,  4, 25]])

### Accessing array rows and columns

One commonly needed routine is accessing single rows or columns of an array. You can do this by combining indexing and slicing, using an empty slice marked by a single colon (:):

In [93]:
print(x2[:, 0])  # first column of x2

[25  5  1]


In [94]:
print(x2[0, :])  # first row of x2

[25  4  2  9]


In the case of row access, the empty slice can be omitted for a more compact syntax:

In [95]:
print(x2[0])  # equivalent to x2[0, :]

[25  4  2  9]


# Subarrays as no-copy views
One important—and extremely useful—thing to know about array slices is that they return views rather than copies of the array data. This is one area in which NumPy array slicing differs from Python list slicing: in lists, slices will be copies. Consider our two-dimensional array from before:

In [96]:
print(x2)

[[25  4  2  9]
 [ 5  3  1  4]
 [ 1  2  3  8]]


Let’s extract a 2×2 subarray from this:

In [97]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[25  4]
 [ 5  3]]


Now if we modify this subarray, we’ll see that the original array is changed! Observe:

In [98]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  4]
 [ 5  3]]


In [99]:
print(x2)

[[99  4  2  9]
 [ 5  3  1  4]
 [ 1  2  3  8]]


This default behavior is actually quite useful: it means that when we work with large datasets, we can access and process pieces of these datasets without the need to copy the underlying data buffer.
## Creating copies of arrays
Despite the nice features of array views, it is sometimes useful to instead explicitly copy the data within an array or a subarray. This can be most easily done with the copy() method:


In [100]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  4]
 [ 5  3]]


If we now modify this subarray, the original array is not touched:

In [103]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  4]
 [ 5  3]]


In [104]:
print(x2)

[[99  4  2  9]
 [ 5  3  1  4]
 [ 1  2  3  8]]


## Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape() method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:


In [105]:
x = np.arange(1, 10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
x.size

9

In [108]:
len(x)

9

In [106]:
 grid = x.reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Another common reshaping pattern is the conversion of a one-dimensional array into a two-dimensional row or column matrix. You can do this with the reshape method, or more easily by making use of the newaxis keyword within a slice operation:

In [134]:
x = np.array([1, 2, 3, 4, 5, 6])
x

array([1, 2, 3, 4, 5, 6])

In [135]:
# row vector via reshape
y = x.reshape((2, 3))
y

array([[1, 2, 3],
       [4, 5, 6]])

In [136]:
y.ndim

2

In [137]:
# row vector via newaxis
z = y[np.newaxis, :]
z
# Note: one bracket is added to the below result

array([[[1, 2, 3],
        [4, 5, 6]]])

In [138]:
z.ndim

3

### Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We’ll take a look at those operations here.
Concatenation of arrays
<br><br>
Concatenation, or joining of two arrays in NumPy, is primarily accomplished through the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a tuple or list of arrays as its first argument, as we can see here:


In [141]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [142]:
x

array([1, 2, 3])

In [143]:
y

array([3, 2, 1])

In [144]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

## You can also concatenate more than two arrays at once:

In [145]:
z = [55, 66, 77]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 55 66 77]


### np.concatenate can also be used for two-dimensional arrays:

In [146]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [147]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [148]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

#### For working with arrays of mixed dimensions, it can be clearer to use the np.vstack (vertical stack) and np.hstack (horizontal stack) functions:


## vstack

In [152]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [153]:
grid = np.array([[9, 8, 7], [6, 5, 4]])
grid 

array([[9, 8, 7],
       [6, 5, 4]])

In [151]:
# vertically stack the arrays
np.([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

## hstack
Similarly, np.dstack will stack arrays along the third axis.

In [155]:
y = np.array([[99],[99]])
y

array([[99],
       [99]])

In [156]:
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

In [157]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x

[1, 2, 3, 99, 99, 3, 2, 1]

In [158]:
x1, x2, x3 = np.split(x, [3, 5])

In [159]:
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N split points lead to N + 1 subarrays. The related functions np.hsplit and np.vsplit are similar:

In [160]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [161]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [162]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Similarly, np.dsplit will split arrays along the third axis.

### Aggregations: Min, Max, and Everything in Between

Often when you are faced with a large amount of data, a first step is to compute summary statistics for the data in question. Perhaps the most common summary statistics are the mean and standard deviation, which allow you to summarize the “typical” values in a dataset, but other aggregates are useful as well (the sum, product, median, minimum and maximum, quantiles, etc.).
<br>
NumPy has fast built-in aggregation functions for working on arrays; we’ll discuss and demonstrate some of them here.
Summing the Values in an Array
<br>
As a quick example, consider computing the sum of all values in an array. Python itself can do this using the built-in sum function:


In [163]:
import numpy as np
L = np.random.random(100)
L

array([0.604246  , 0.99279658, 0.54753523, 0.62043961, 0.2197822 ,
       0.40349807, 0.24540153, 0.20670218, 0.50776338, 0.56485794,
       0.35450987, 0.75362043, 0.24975566, 0.90037571, 0.10335014,
       0.35880936, 0.80280714, 0.27238134, 0.0744555 , 0.68355499,
       0.94752066, 0.04302739, 0.67242452, 0.58604984, 0.42416793,
       0.97984691, 0.48525972, 0.28275643, 0.7428833 , 0.34315348,
       0.33557842, 0.14844795, 0.40201002, 0.52304063, 0.11589413,
       0.96755295, 0.88181907, 0.42177726, 0.43168117, 0.71331746,
       0.99481831, 0.04558452, 0.82419531, 0.57792394, 0.8657677 ,
       0.29802164, 0.11777741, 0.77997228, 0.87847922, 0.74307803,
       0.15222199, 0.36309042, 0.97129528, 0.78291701, 0.2355855 ,
       0.99621103, 0.27557631, 0.08067324, 0.93308706, 0.57611693,
       0.53961378, 0.02080383, 0.52747497, 0.35724244, 0.05518018,
       0.3706963 , 0.13699538, 0.47816858, 0.49478975, 0.95231647,
       0.65821421, 0.13535264, 0.26742704, 0.45952962, 0.11364

In [164]:
sum(L)

50.601380434881015

The syntax is quite similar to that of NumPy’s sum function, and the result is the same in the simplest case:

In [165]:
np.sum(L)

50.60138043488102

However, because it executes the operation in compiled code, NumPy’s version of the operation is computed much more quickly:

In [166]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

75.5 ms ± 2.61 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
615 µs ± 27.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Be careful, though: the sum function and the np.sum function are not identical, which can sometimes lead to confusion! In particular, their optional arguments have different meanings, and np.sum is aware of multiple array dimensions, as we will see in the following section.
### Minimum and Maximum

Similarly, Python has built-in min and max functions, used to find the minimum value and maximum value of any given array:

In [167]:
min(big_array), max(big_array)

(1.075103116532361e-07, 0.999997997848197)

NumPy’s corresponding functions have similar syntax, and again operate much more quickly:

In [168]:
np.min(big_array), np.max(big_array)

(1.075103116532361e-07, 0.999997997848197)

In [169]:
%timeit min(big_array)
%timeit np.min(big_array)

57.1 ms ± 2.43 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
806 µs ± 80.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


For min, max, sum, and several other NumPy aggregates, a shorter syntax is to use methods of the array object itself:

In [170]:
print(big_array.min(), big_array.max(), big_array.sum())

1.075103116532361e-07 0.999997997848197 499617.26594171295


Whenever possible, make sure that you are using the NumPy version of these aggregates when operating on NumPy arrays!
Multidimensional aggregates
<br>
One common type of aggregation operation is an aggregate along a row or column. Say you have some data stored in a two-dimensional array:

In [171]:
M = np.random.random((3, 4))
print(M)

[[0.25191174 0.32387439 0.26226    0.81825279]
 [0.9878579  0.85102945 0.6303516  0.21488163]
 [0.51914128 0.82842155 0.80837067 0.68784608]]


By default, each NumPy aggregation function will return the aggregate over the entire array:

In [172]:
M.sum()

7.18419908695078

Aggregation functions take an additional argument specifying the axis along which the aggregate is computed. For example, we can find the minimum value within each column by specifying axis=0:

In [173]:
M.min(axis=0)

array([0.25191174, 0.32387439, 0.26226   , 0.21488163])

The function returns four values, corresponding to the four columns of numbers.
<br>
Similarly, we can find the maximum value within each row:

In [174]:
M.max(axis=1)

array([0.81825279, 0.9878579 , 0.82842155])

The way the axis is specified here can be confusing to users coming from other languages. The axis keyword specifies the dimension of the array that will be collapsed, rather than the dimension that will be returned. So specifying axis=0 means that the first axis will be collapsed: for two-dimensional arrays, this means that values within each column will be aggregated.
### Other aggregation functions

NumPy provides many other aggregation functions, but we won’t discuss them in detail here. Additionally, most aggregates have a NaN-safe counterpart that computes the result while ignoring missing values, which are marked by the special IEEE floating-point NaN value (for a fuller discussion of missing data, see “Handling Missing Data”). Some of these NaN-safe functions were not added until NumPy 1.8, so they will not be available in older NumPy versions.

**np.sum**: Compute sum of elements
<br>
**np.prod**: Compute product of elements
<br>
**np.mean**: Compute median of elements
<br>
**np.std**: Compute standard deviation
<br>
**np.var**: Compute variance
<br>
**np.min**: Find minimum value
<br>
**np.max**: Find maximum value
<br>
**np.argmin**: Find index of minimum value
<br>
**np.argmax**: Find index of maximum value
<br>
**np.median**: Compute median of elements
<br>
**np.percentile**: Compute rank-based statistics of elements
<br>
**np.any**: Evaluate whether any elements are true
<br>
**np.all**: Evaluate whether all elements are true

## Computation on Arrays: Broadcasting

Broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, multiplication, etc.) on arrays of different sizes.

### Introducing Broadcasting

Recall that for arrays of the same size, binary operations are performed on an element-by-element basis:

In [188]:
import numpy as np

a = np.array([0, 1, 2])
b = np.array([5, 5, 5])

In [189]:
a

array([0, 1, 2])

In [190]:
b

array([5, 5, 5])

In [191]:
a + b

array([5, 6, 7])

Broadcasting allows these types of binary operations to be performed on arrays of different sizes—for example, we can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [192]:
a + 5

array([5, 6, 7])

We can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy’s broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.
<br>
We can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:

In [193]:
M = np.ones((3, 3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [194]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

Here the one-dimensional array a is stretched, or broadcast, across the second dimension in order to match the shape of M.
<br>
While these examples are relatively easy to understand, more complicated cases can involve broadcasting of both arrays. Consider the following example:


In [195]:
a

array([0, 1, 2])

In [196]:
b

array([5, 5, 5])

In [197]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

In [198]:
a

array([0, 1, 2])

In [199]:
b

array([[0],
       [1],
       [2]])

In [201]:
print(a)

[0 1 2]


In [202]:
print(b)

[[0]
 [1]
 [2]]


In [203]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### Rules of Broadcasting

Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:
<br>
**Rule 1:** If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
<br><br>
**Rule 2:** If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
<br>  
**Rule 3:** If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

___

In [211]:
M = np.ones((2, 3))
a = np.arange(3)

In [212]:
print(M)

[[1. 1. 1.]
 [1. 1. 1.]]


In [213]:
print(a)

[0 1 2]


In [215]:
a.shape

(3,)

In [214]:
M.shape

(2, 3)

In [216]:
a[:, np.newaxis].shape

(3, 1)

In [219]:
X = np.random.random((10, 3))
X

array([[0.6768055 , 0.10123066, 0.35909626],
       [0.86778846, 0.48577024, 0.10720127],
       [0.03323111, 0.93190185, 0.66586249],
       [0.25456377, 0.0357642 , 0.52572357],
       [0.67519683, 0.47157486, 0.7641603 ],
       [0.1109926 , 0.64939225, 0.18872043],
       [0.60999291, 0.93270056, 0.86850054],
       [0.77213304, 0.95184451, 0.04968181],
       [0.14143257, 0.44417619, 0.8529571 ],
       [0.60920704, 0.48871163, 0.98125881]])

In [220]:
X.size

30

In [221]:
X.ndim

2

We can compute the mean of each feature using the mean aggregate across the first dimension:

In [223]:
Xmean = X.mean(0)
Xmean

array([0.47513438, 0.5493067 , 0.53631626])

In [225]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [226]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [227]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [228]:
np.sum(x < 6)

8

The benefit of sum() is that like with other NumPy aggregation functions, this summation can be done along rows or columns as well:

In [229]:
# how many values less than 6 in each row?
np.sum(x < 6, axis=1)

array([4, 2, 2])

This counts the number of values less than 6 in each row of the matrix.
<br><br>
If we’re interested in quickly checking whether any or all the values are true, we can use (you guessed it) np.any() or np.all():

In [230]:
# are there any values greater than 8?
np.any(x > 8)

True

In [231]:
# are there any values less than zero?
np.any(x < 0)

False

In [232]:
# are all values less than 10?
np.all(x < 10)

True

In [233]:
# are all values equal to 6?
np.all(x == 6)

False

np.all() and np.any() can be used along particular axes as well. For example:

In [234]:
# are all values in each row less than 8?
np.all(x < 8, axis=1)

array([ True, False,  True])

In [236]:
import numpy as np
import pandas as pd

/home/sara/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/sara/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [237]:
rainfall = pd.read_csv('data/Seattle2014.csv')['PRCP'].values

In [238]:
rainfall.shape

(365,)

In [239]:
inches = rainfall / 254  # 1/10mm -> inches
inches.shape

(365,)

In [240]:
print("Number days without rain:      ", np.sum(inches == 0))
print("Number days with rain:         ", np.sum(inches != 0))
print("Days with more than 0.5 inches:", np.sum(inches > 0.5))
print("Rainy days with < 0.1 inches  :", np.sum((inches > 0) & (inches < 0.2)))

Number days without rain:       215
Number days with rain:          150
Days with more than 0.5 inches: 37
Rainy days with < 0.1 inches  : 75


In [241]:
# construct a mask of all rainy days
rainy = (inches > 0)

# construct a mask of all summer days (June 21st is the 172nd day)
summer = (np.arange(365) - 172 < 90) & (np.arange(365) - 172 > 0)

print("Median precip on rainy days in 2014 (inches):   ", np.median(inches[rainy]))
print("Median precip on summer days in 2014 (inches):  ", np.median(inches[summer]))
print("Maximum precip on summer days in 2014 (inches): ", np.max(inches[summer]))
print("Median precip on non-summer rainy days (inches):", np.median(inches[rainy & ~summer]))

Median precip on rainy days in 2014 (inches):    0.19488188976377951
Median precip on summer days in 2014 (inches):   0.0
Maximum precip on summer days in 2014 (inches):  0.8503937007874016
Median precip on non-summer rainy days (inches): 0.20078740157480315
