For linear algebra, using matrices might be more straightforward. The matrix object in NumPy inherits all the attributes and methods from **ndarray**, but it's strictly two-dimensional, while **ndarray** can be multi-dimensional. The well-known advantage of using NumPy matrices is that they provide matrix multiplication as the **<font color="blue"> * </font>**  notation; for example, if <font color="blue">x</font> and <font color="blue">y</font> are matrices, <font color="blue">x * y</font> is their matrix product. 

In [1]:
import numpy as np 


ndArray = np.arange(9).reshape(3,3) 
x = np.matrix(ndArray) 

In [2]:
x 

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [5]:
x.ndim, x.shape

(2, (3, 3))

In [3]:
y = np.mat(np.identity(3))

In [4]:
x 

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
y.ndim, y.shape

(2, (3, 3))

There are a couple of ways to create or convert to a NumPy matrix object, and the more preferred way is to use <font color="blue">numpy.mat()</font> or <font color="blue">numpy.matrix()</font>. Both methods create matrices, but numpy.matrix() creates a copy while numpy.mat() changes the view only; it's equivalent to <font color="blue">numpy.matrix(data, copy = False)</font>. In the previous example, we create two matrices, both of which are from the ndarray object (the np.identity(3) returns a 3 x 3 identity array). 

In [8]:
z = x + y
z

matrix([[1., 1., 2.],
        [3., 5., 5.],
        [6., 7., 9.]])

In [9]:
z.ndim, z.shape

(2, (3, 3))